# Generated by Django 5.0.1 on 2024-02-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('clave', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Clave:')),
                ('name', models.CharField(default='categoria', max_length=32, verbose_name='Categoria:')),
                ('descripcion', models.CharField(default='Descripcion...', max_length=360, verbose_name='Descripcion:')),
            ],
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('noCiudad', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='No. Ciudad:')),
                ('name', models.CharField(default='ciudad', max_length=32, verbose_name='Ciudad:')),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('noCompra', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='No. Compra:')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha de Compra:')),
                ('totalPago', models.FloatField(default=0.0, verbose_name='Total del Pago:')),
            ],
        ),
        migrations.CreateModel(
            name='entidad_F',
            fields=[
                ('clave', models.CharField(default='clave', max_length=6, primary_key=True, serialize=False, verbose_name='Clave:')),
                ('name', models.CharField(default='entidad federativa', max_length=32, verbose_name='Entidad Federativa:')),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código:')),
                ('descripcion', models.CharField(default='descripcion...', max_length=16, verbose_name='Descripción:')),
            ],
        ),
        migrations.CreateModel(
            name='metoPago',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código:')),
                ('namePago', models.CharField(max_length=32, verbose_name='Metodo de Pago:')),
            ],
        ),
        migrations.CreateModel(
            name='paqueteria',
            fields=[
                ('clave', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Clave:')),
                ('name', models.CharField(default='paqueteria', max_length=32, verbose_name='Nombre Paqueteria:')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Código:')),
                ('name', models.CharField(default='nombre del proveedor', max_length=32, verbose_name='Proovedor:')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('noCliente', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='No. Cliente:')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre(s):')),
                ('apPat', models.CharField(max_length=32, verbose_name='Apellido Paterno:')),
                ('apMat', models.CharField(max_length=32, verbose_name='Apellido Materno:')),
                ('edad', models.IntegerField(default=0, verbose_name='Edad:')),
                ('numCel', models.CharField(max_length=20, verbose_name='Teléfono:')),
                ('email', models.CharField(max_length=32, verbose_name='Email:')),
                ('colonia', models.CharField(max_length=32, verbose_name='Colonia:')),
                ('calle', models.CharField(max_length=32, verbose_name='Calle:')),
                ('noCasa', models.CharField(max_length=8, verbose_name='No. Casa:')),
                ('cp', models.CharField(max_length=5, verbose_name='CP:')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ciudad')),
                ('entidad_F', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidad_f')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='entidad_F',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidad_f'),
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('sku', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='SKU:')),
                ('name', models.CharField(default='nombre del producto', max_length=64, verbose_name='Producto:')),
                ('descripcion', models.CharField(default='Descripcion...', max_length=200, verbose_name='Descripcion:')),
                ('precioVen', models.FloatField(default=0.0, verbose_name='Precio:')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock:')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='compra_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad:')),
                ('precioCom', models.FloatField(default=0.0, verbose_name='Precio Compra:')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compra')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor'),
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('noVenta', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='No. Venta:')),
                ('totalPagar', models.FloatField(default=0.0, verbose_name='Total a pagar:')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha de Venta:')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('noPago', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='No. Pago:')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha de Pago')),
                ('metoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metopago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('noEntrega', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='No. Entrega:')),
                ('fechaSalida', models.DateField(verbose_name='Fecha de Salida:')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha de Entrega:')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('paqueteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paqueteria')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='venta_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=16, verbose_name='Cantidad:')),
                ('importe', models.FloatField(default=0.0, verbose_name='Importe:')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
    ]
